### ISSUE TITLE
Combo Action Input System

### ISSUE THREAD

**Issue by usernameSplash** [usernameSplash/YoumuPlayer#1]
## Combo Action Input System
주로 격투게임 등에서 사용되는 콤보 액션을 처리하기 위한 입력 시스템을 구축한다.

### 아이디어

ulong 자료형은 64비트 정수이다.

64비트를 8비트씩 8구역으로 나눌 수 있다.

8개의 각 구역을 8개의 key에 각각 할당한다. (예 : W, A, S, D, 공격1, 공격2, 공격3, 공격4 버튼)

```C#
// 16진수의 한 자리는 4비트이므로 아래와 같이 할당한다.
ulong A = 0x1;
ulong W = 0x100;
ulong S = 0x10000;
...
```
위와 같이 8비트 간격으로 떨어뜨린 8개의 구역을 준비한다.

그렇다면 커맨드는

```
ulong Command = 0;

Command |= A;
Command |= W;
```
이런 식으로 A + W 입력을 표현할 수 있다.

이 때, 비트가 겹칠 우려가 있다. 예를 들어 A+A로 대쉬를 하려는 경우
`Command |= A;`를 두 번 하는 것은 의미가 없기 때문이다.

또 하나의 문제는 `W + A`와 `A + W`, 키의 구성은 같지만 순서가 다른 두 커맨드의 구별이 불가능하다는 점이다.

이 문제를 해결하기 위해, 지금까지 입력된 커맨드의 수를 `commandCount` 따위의 변수로 따로 저장하여

`Command |= (any Command) << commandCount`

비트 시프트 연산을 통해 n번째 커맨드를 따로 기록한다.

### 예시
A, J, W가 순서대로 입력되어 구성되는 커맨드는

```C#
Command |= A;
Command |= J << 1;
Command |= W << 2;
```
와 같다.

**Comment by usernameSplash** [comment]
## Update, Reset Command 
커맨드가 초기화, 또는 갱신되는 경우는 다음과 같다.

### 초기화되는 경우
* 하나의 커맨드가 완성될 때. (Command List에 등록된 값들과 현재 커맨드가 일치할 때)

### 갱신되는 경우
* 어떤 키가 입력되고 일정 시간이 지난 경우. (키가 입력될 때 마다 코루틴 호출, n초 후 `Command >> 1` 연산 적용하여 가장 오래된 비트 버리기)

**Comment by usernameSplash** [comment]
## 예상되는 문제점

예를 들어 `D+D` 입력을 처리하는 `DashCommand`란 커맨드 변수가 있다고 가정한다. 

만약 사용자에 의해 입력이 `A, D, D`로 주어졌다면, 위 공식에 의해 도출된 `Command`와 `DashCommand` 변수는 다르기 때문에 커맨드를 인식하지 못하지만, 실제로는 `D+D` 가 입력된 것이었으므로 대쉬를 해야 한다.

이 부분을 어떻게 처리해야 할 지 모르겠다.

**Comment by usernameSplash** [comment]
## 문제점 해결 방법 아이디어 
키가 입력될 때 마다 모든 커맨드(`CommandList`의 각 요소)에 대해 현재 입력된 값(key의 고유값에 `commandCount`만큼 shift한 값)을 and 연산을 진행해보고, 모든 커맨드들에 대해 0이 나온다면 커맨드를 초기화한다.

**Comment by Hulkstd** [comment]
콤보에 관해 저장할 때
```c#
[Flags]
public enum Combo
{
    None = 0,
    A = 1 << 1,  // 또는 A = 1
    B = 1 << 2,  // 또는 B = 2
    D = 1 << 3.  // 또는 C = 4 
}
```
이런식으로 이용하거나. (참조링크[⑴](https://docs.microsoft.com/ko-kr/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags))

![image](https://user-images.githubusercontent.com/36978533/94541274-59c4b600-0282-11eb-8f92-f765c5af4f8b.png)
위 사진처럼 Inspector 상에서도 확인 하고 싶을 경우
```c#
public enum Combo
{
    None = 0,
    A = 1,
    B = 2.
    C = 4,
    AAndB = 3,
    AAndC = 5,
    BAndC = 6,
    AAndBAndC = 7,
}
```
처럼 열거형을 선언 후 `CustomPropertyEditor`을 이용하여(참고링크[②](https://wergia.tistory.com/104)) 사진과 같이 출력하는 방법을 사용하는것이 좋을것으로 보입니다.
